package common

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/site24x7/terraform-provider-site24x7/site24x7"
)

var attributeAlertGroupDataSourceSchema = map[string]*schema.Schema{
	"group_id": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Unique ID generated by the server for the attribute alert group.",
	},
	"display_name": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Display name for the attribute alert group.",
	},
	"attribute_list": {
		Type:        schema.TypeList,
		Computed:    true,
		Elem:        &schema.Schema{Type: schema.TypeInt},
		Description: "List of attribute IDs associated to the group.",
	},
}

func DataSourceSite24x7AttributeAlertGroup() *schema.Resource {
	return &schema.Resource{
		Read:   dataSourceSite24x7AttributeAlertGroupRead,
		Schema: attributeAlertGroupDataSourceSchema,
	}
}

func dataSourceSite24x7AttributeAlertGroupRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	groupID := d.Get("group_id").(string)

	group, err := client.AttributeAlertGroup().Get(groupID)
	if err != nil {
		return err
	}

	d.SetId(group.GroupID)
	d.Set("display_name", group.DisplayName)
	d.Set("attribute_list", group.AttributeList)

	return nil
}
