package common

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/site24x7/terraform-provider-site24x7/api"
	"github.com/site24x7/terraform-provider-site24x7/site24x7"
)

var attributeAlertGroupSchema = map[string]*schema.Schema{
	"display_name": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Display name for the attribute alert group.",
	},
	"attribute_list": {
		Type:        schema.TypeList,
		Required:    true,
		Elem:        &schema.Schema{Type: schema.TypeInt},
		Description: "List of attribute IDs to be associated to the group. Refer attribute details for valid IDs.",
	},
	// Computed
	"group_id": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Unique ID generated by the server for the attribute alert group.",
	},
}

func ResourceSite24x7AttributeAlertGroup() *schema.Resource {
	return &schema.Resource{
		Create: resourceSite24x7AttributeAlertGroupCreate,
		Read:   resourceSite24x7AttributeAlertGroupRead,
		Update: resourceSite24x7AttributeAlertGroupUpdate,
		Delete: resourceSite24x7AttributeAlertGroupDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: attributeAlertGroupSchema,
	}
}

func resourceSite24x7AttributeAlertGroupCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	group := resourceDataToAttributeAlertGroup(d)

	created, err := client.AttributeAlertGroup().Create(group)
	if err != nil {
		return err
	}

	d.SetId(created.GroupID)
	return resourceSite24x7AttributeAlertGroupRead(d, meta)
}

func resourceSite24x7AttributeAlertGroupRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	group, err := client.AttributeAlertGroup().Get(d.Id())
	if err != nil {
		return err
	}

	updateAttributeAlertGroupResourceData(d, group)
	return nil
}

func resourceSite24x7AttributeAlertGroupUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	group := resourceDataToAttributeAlertGroup(d)
	group.GroupID = d.Id()

	updated, err := client.AttributeAlertGroup().Update(group)
	if err != nil {
		return err
	}

	d.SetId(updated.GroupID)
	return resourceSite24x7AttributeAlertGroupRead(d, meta)
}

func resourceSite24x7AttributeAlertGroupDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	err := client.AttributeAlertGroup().Delete(d.Id())
	if err != nil {
		return err
	}

	d.SetId("")
	return nil
}

func resourceDataToAttributeAlertGroup(d *schema.ResourceData) *api.AttributeAlertGroup {
	attrListRaw := d.Get("attribute_list").([]interface{})
	attrList := make([]int, len(attrListRaw))
	for i, v := range attrListRaw {
		attrList[i] = v.(int)
	}

	return &api.AttributeAlertGroup{
		DisplayName:   d.Get("display_name").(string),
		AttributeList: attrList,
	}
}

func updateAttributeAlertGroupResourceData(d *schema.ResourceData, group *api.AttributeAlertGroup) {
	d.Set("group_id", group.GroupID)
	d.Set("display_name", group.DisplayName)
	d.Set("attribute_list", group.AttributeList)
}
