package common

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/site24x7/terraform-provider-site24x7/api"
	"github.com/site24x7/terraform-provider-site24x7/site24x7"
)

var oauth2ProviderSchema = map[string]*schema.Schema{
	"provider_name": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "A name to identify this OAuth provider in the dashboard.",
	},
	"oauth2_flow": {
		Type:        schema.TypeInt,
		Required:    true,
		Description: "The grant type of the OAuth provider. Use 2 for Client Credentials, 3 for Resource Owner Password Credentials.",
	},
	"client_id": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "The client ID obtained from your OAuth provider.",
	},
	"client_secret": {
		Type:        schema.TypeString,
		Required:    true,
		Sensitive:   true,
		Description: "The client secret obtained from your OAuth provider.",
	},
	"access_token_uri": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "The API Token Endpoint of the OAuth 2 Provider.",
	},
	"send_token_as": {
		Type:        schema.TypeList,
		Required:    true,
		MaxItems:    1,
		Description: "Specifies if the access token will be sent via query parameters or request headers.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"method": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Method to send token. H for Header, Q for Query parameter.",
				},
				"name": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Query parameter name or header name.",
				},
				"value": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Query parameter value or header value.",
				},
			},
		},
	},
	"auth_method": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Specifies the authentication method to be used for sending the Client ID and Client Secret to the authorization server.",
	},
	"auth_user": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Resource owner's username. Required when oauth2_flow is 3 (Resource Owner Password Credentials).",
	},
	"auth_pass": {
		Type:        schema.TypeString,
		Optional:    true,
		Sensitive:   true,
		Description: "Resource owner's password. Required when oauth2_flow is 3 (Resource Owner Password Credentials).",
	},
	"request_body": {
		Type:        schema.TypeList,
		Optional:    true,
		Description: "Specifies the parameters to be sent in the request body.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"name": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Parameter name.",
				},
				"value": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Parameter value.",
				},
			},
		},
	},
	"user_group_ids": {
		Type:        schema.TypeList,
		Optional:    true,
		Elem:        &schema.Schema{Type: schema.TypeString},
		Description: "List of User Groups that are notified when an access token can't be refreshed even after three consecutive retries.",
	},
	// Computed attributes (returned by the API)
	"provider_id": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Unique ID generated by the server for the OAuth provider.",
	},
	"access_token": {
		Type:        schema.TypeString,
		Computed:    true,
		Sensitive:   true,
		Description: "An access token used for authorization and authentication.",
	},
	"auto_reauthorize": {
		Type:        schema.TypeBool,
		Computed:    true,
		Description: "Automatic reauthorization for fetching access token when refresh token fails.",
	},
	"expiry_time": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Expiration time for the current access token.",
	},
}

func ResourceSite24x7OAuth2Provider() *schema.Resource {
	return &schema.Resource{
		Create: resourceSite24x7OAuth2ProviderCreate,
		Read:   resourceSite24x7OAuth2ProviderRead,
		Update: resourceSite24x7OAuth2ProviderUpdate,
		Delete: resourceSite24x7OAuth2ProviderDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: oauth2ProviderSchema,
	}
}

func resourceSite24x7OAuth2ProviderCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	oauth2Provider := resourceDataToOAuth2Provider(d)

	provider, err := client.OAuth2Provider().Create(oauth2Provider)
	if err != nil {
		return err
	}

	d.SetId(provider.ProviderID)
	return resourceSite24x7OAuth2ProviderRead(d, meta)
}

func resourceSite24x7OAuth2ProviderRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	provider, err := client.OAuth2Provider().Get(d.Id())
	if err != nil {
		return err
	}

	updateOAuth2ProviderResourceData(d, provider)
	return nil
}

func resourceSite24x7OAuth2ProviderUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	oauth2Provider := resourceDataToOAuth2Provider(d)
	oauth2Provider.ProviderID = d.Id()

	provider, err := client.OAuth2Provider().Update(oauth2Provider)
	if err != nil {
		return err
	}

	d.SetId(provider.ProviderID)
	return resourceSite24x7OAuth2ProviderRead(d, meta)
}

func resourceSite24x7OAuth2ProviderDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	err := client.OAuth2Provider().Delete(d.Id())
	if err != nil {
		return err
	}

	d.SetId("")
	return nil
}

func resourceDataToOAuth2Provider(d *schema.ResourceData) *api.OAuth2Provider {
	provider := &api.OAuth2Provider{
		ProviderName:   d.Get("provider_name").(string),
		OAuth2Flow:     d.Get("oauth2_flow").(int),
		ClientID:       d.Get("client_id").(string),
		ClientSecret:   d.Get("client_secret").(string),
		AccessTokenURI: d.Get("access_token_uri").(string),
	}

	if v, ok := d.GetOk("auth_method"); ok {
		provider.AuthMethod = v.(string)
	}
	if v, ok := d.GetOk("auth_user"); ok {
		provider.AuthUser = v.(string)
	}
	if v, ok := d.GetOk("auth_pass"); ok {
		provider.AuthPass = v.(string)
	}

	// send_token_as
	sendTokenAsList := d.Get("send_token_as").([]interface{})
	if len(sendTokenAsList) > 0 {
		sendTokenAsMap := sendTokenAsList[0].(map[string]interface{})
		provider.SendTokenAs = &api.SendTokenAs{
			Method: sendTokenAsMap["method"].(string),
			Name:   sendTokenAsMap["name"].(string),
			Value:  sendTokenAsMap["value"].(string),
		}
	}

	// request_body
	if v, ok := d.GetOk("request_body"); ok {
		requestBodyList := v.([]interface{})
		requestBody := make([]api.RequestBodyParam, len(requestBodyList))
		for i, item := range requestBodyList {
			itemMap := item.(map[string]interface{})
			requestBody[i] = api.RequestBodyParam{
				Name:  itemMap["name"].(string),
				Value: itemMap["value"].(string),
			}
		}
		provider.RequestBody = requestBody
	}

	// user_group_ids
	if v, ok := d.GetOk("user_group_ids"); ok {
		userGroupIDsList := v.([]interface{})
		userGroupIDs := make([]string, len(userGroupIDsList))
		for i, id := range userGroupIDsList {
			userGroupIDs[i] = id.(string)
		}
		provider.UserGroupIDs = userGroupIDs
	}

	return provider
}

func updateOAuth2ProviderResourceData(d *schema.ResourceData, provider *api.OAuth2Provider) {
	d.Set("provider_id", provider.ProviderID)
	d.Set("provider_name", provider.ProviderName)
	d.Set("oauth2_flow", provider.OAuth2Flow)
	d.Set("client_id", provider.ClientID)
	d.Set("client_secret", provider.ClientSecret)
	d.Set("access_token_uri", provider.AccessTokenURI)
	d.Set("auth_method", provider.AuthMethod)
	d.Set("auth_user", provider.AuthUser)
	d.Set("auth_pass", provider.AuthPass)
	d.Set("access_token", provider.AccessToken)
	d.Set("auto_reauthorize", provider.AutoReauthorize)
	d.Set("expiry_time", provider.ExpiryTime)

	if provider.SendTokenAs != nil {
		d.Set("send_token_as", []map[string]interface{}{
			{
				"method": provider.SendTokenAs.Method,
				"name":   provider.SendTokenAs.Name,
				"value":  provider.SendTokenAs.Value,
			},
		})
	}

	if provider.RequestBody != nil {
		requestBody := make([]map[string]interface{}, len(provider.RequestBody))
		for i, param := range provider.RequestBody {
			requestBody[i] = map[string]interface{}{
				"name":  param.Name,
				"value": param.Value,
			}
		}
		d.Set("request_body", requestBody)
	}

	if provider.UserGroupIDs != nil {
		d.Set("user_group_ids", provider.UserGroupIDs)
	}
}
