package common

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/site24x7/terraform-provider-site24x7/site24x7"
)

var oauth2ProviderDataSourceSchema = map[string]*schema.Schema{
	"provider_id": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Unique ID generated by the server for the OAuth provider.",
	},
	"provider_name": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "A name to identify this OAuth provider in the dashboard.",
	},
	"oauth2_flow": {
		Type:        schema.TypeInt,
		Computed:    true,
		Description: "The grant type of the OAuth provider.",
	},
	"client_id": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "The client ID obtained from your OAuth provider.",
	},
	"access_token_uri": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "The API Token Endpoint of the OAuth 2 Provider.",
	},
	"auth_method": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Authentication method for sending Client ID and Client Secret.",
	},
	"send_token_as": {
		Type:     schema.TypeList,
		Computed: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"method": {
					Type:     schema.TypeString,
					Computed: true,
				},
				"name": {
					Type:     schema.TypeString,
					Computed: true,
				},
				"value": {
					Type:     schema.TypeString,
					Computed: true,
				},
			},
		},
	},
	"user_group_ids": {
		Type:     schema.TypeList,
		Computed: true,
		Elem:     &schema.Schema{Type: schema.TypeString},
	},
	"expiry_time": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"auto_reauthorize": {
		Type:     schema.TypeBool,
		Computed: true,
	},
}

func DataSourceSite24x7OAuth2Provider() *schema.Resource {
	return &schema.Resource{
		Read:   dataSourceSite24x7OAuth2ProviderRead,
		Schema: oauth2ProviderDataSourceSchema,
	}
}

func dataSourceSite24x7OAuth2ProviderRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	providerID := d.Get("provider_id").(string)

	provider, err := client.OAuth2Provider().Get(providerID)
	if err != nil {
		return err
	}

	d.SetId(provider.ProviderID)
	d.Set("provider_name", provider.ProviderName)
	d.Set("oauth2_flow", provider.OAuth2Flow)
	d.Set("client_id", provider.ClientID)
	d.Set("access_token_uri", provider.AccessTokenURI)
	d.Set("auth_method", provider.AuthMethod)
	d.Set("expiry_time", provider.ExpiryTime)
	d.Set("auto_reauthorize", provider.AutoReauthorize)

	if provider.SendTokenAs != nil {
		d.Set("send_token_as", []map[string]interface{}{
			{
				"method": provider.SendTokenAs.Method,
				"name":   provider.SendTokenAs.Name,
				"value":  provider.SendTokenAs.Value,
			},
		})
	}

	if provider.UserGroupIDs != nil {
		d.Set("user_group_ids", provider.UserGroupIDs)
	}

	return nil
}
