package common

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/site24x7/terraform-provider-site24x7/site24x7"
)

var slaSettingDataSourceSchema = map[string]*schema.Schema{
	"sla_id": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Unique ID generated by the server for the SLA.",
	},
	"display_name": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Display name for the SLA.",
	},
	"type": {
		Type:        schema.TypeInt,
		Computed:    true,
		Description: "Type of SLA.",
	},
	"description": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Description for the SLA.",
	},
	"selection_type": {
		Type:        schema.TypeInt,
		Computed:    true,
		Description: "Resource type associated to this SLA Report.",
	},
	"monitors": {
		Type:     schema.TypeList,
		Computed: true,
		Elem:     &schema.Schema{Type: schema.TypeString},
	},
	"monitor_groups": {
		Type:     schema.TypeList,
		Computed: true,
		Elem:     &schema.Schema{Type: schema.TypeString},
	},
	"business_hours_id": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"sla_targets": {
		Type:     schema.TypeList,
		Computed: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"target_id": {
					Type:     schema.TypeString,
					Computed: true,
				},
				"target_name": {
					Type:     schema.TypeString,
					Computed: true,
				},
				"target_color": {
					Type:     schema.TypeString,
					Computed: true,
				},
				"target_condition": {
					Type:     schema.TypeInt,
					Computed: true,
				},
				"target_value": {
					Type:     schema.TypeFloat,
					Computed: true,
				},
			},
		},
	},
	"slo_availability": {
		Type:     schema.TypeList,
		Computed: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"availability": {
					Type:     schema.TypeFloat,
					Computed: true,
				},
				"condition": {
					Type:     schema.TypeInt,
					Computed: true,
				},
				"weightage": {
					Type:     schema.TypeInt,
					Computed: true,
				},
			},
		},
	},
	"slo_responsetime": {
		Type:     schema.TypeList,
		Computed: true,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"responsetime": {
					Type:     schema.TypeFloat,
					Computed: true,
				},
				"time_available": {
					Type:     schema.TypeFloat,
					Computed: true,
				},
				"condition": {
					Type:     schema.TypeInt,
					Computed: true,
				},
				"weightage": {
					Type:     schema.TypeInt,
					Computed: true,
				},
			},
		},
	},
}

func DataSourceSite24x7SLASetting() *schema.Resource {
	return &schema.Resource{
		Read:   dataSourceSite24x7SLASettingRead,
		Schema: slaSettingDataSourceSchema,
	}
}

func dataSourceSite24x7SLASettingRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	slaID := d.Get("sla_id").(string)

	sla, err := client.SLASetting().Get(slaID)
	if err != nil {
		return err
	}

	d.SetId(sla.SLAID)
	d.Set("display_name", sla.DisplayName)
	d.Set("type", sla.Type)
	d.Set("description", sla.Description)
	d.Set("selection_type", sla.SelectionType)
	d.Set("business_hours_id", sla.BusinessHoursID)

	if sla.Monitors != nil {
		d.Set("monitors", sla.Monitors)
	}
	if sla.MonitorGroups != nil {
		d.Set("monitor_groups", sla.MonitorGroups)
	}

	// sla_targets
	if sla.SLATargets != nil {
		targets := make([]map[string]interface{}, len(sla.SLATargets))
		for i, t := range sla.SLATargets {
			targets[i] = map[string]interface{}{
				"target_id":        t.TargetID,
				"target_name":      t.TargetName,
				"target_color":     t.TargetColor,
				"target_condition": t.TargetCondition,
				"target_value":     t.TargetValue,
			}
		}
		d.Set("sla_targets", targets)
	}

	// slo_availability
	if sla.SLOAvailability != nil {
		d.Set("slo_availability", []map[string]interface{}{
			{
				"availability": sla.SLOAvailability.Availability,
				"condition":    sla.SLOAvailability.Condition,
				"weightage":    sla.SLOAvailability.Weightage,
			},
		})
	}

	// slo_responsetime
	if sla.SLOResponseTime != nil {
		d.Set("slo_responsetime", []map[string]interface{}{
			{
				"responsetime":   sla.SLOResponseTime.ResponseTime,
				"time_available": sla.SLOResponseTime.TimeAvailable,
				"condition":      sla.SLOResponseTime.Condition,
				"weightage":      sla.SLOResponseTime.Weightage,
			},
		})
	}

	return nil
}
