package common

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/site24x7/terraform-provider-site24x7/api"
	"github.com/site24x7/terraform-provider-site24x7/site24x7"
)

var slaSettingSchema = map[string]*schema.Schema{
	"display_name": {
		Type:        schema.TypeString,
		Required:    true,
		Description: "Display name for the SLA.",
	},
	"type": {
		Type:        schema.TypeInt,
		Required:    true,
		Description: "Type of SLA. 1 - Availability, 2 - Response time, 3 - Composite.",
	},
	"description": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "Description for the SLA.",
	},
	"selection_type": {
		Type:        schema.TypeInt,
		Required:    true,
		Description: "Resource type for which the SLA Report has to be generated. Associate multiple monitors or all monitors in a group.",
	},
	"monitors": {
		Type:        schema.TypeList,
		Optional:    true,
		Elem:        &schema.Schema{Type: schema.TypeString},
		Description: "Monitor IDs to be associated with the SLA Report. Required if selection_type is Monitor IDs.",
	},
	"monitor_groups": {
		Type:        schema.TypeList,
		Optional:    true,
		Elem:        &schema.Schema{Type: schema.TypeString},
		Description: "Monitor Groups to associate all related monitors to the SLA Report. Required if selection_type is Monitor Groups.",
	},
	"business_hours_id": {
		Type:        schema.TypeString,
		Optional:    true,
		Description: "The predefined business hours during which critical outage details reports are generated.",
	},
	"sla_targets": {
		Type:        schema.TypeList,
		Required:    true,
		Description: "Targets to be achieved for this SLA.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"target_id": {
					Type:        schema.TypeString,
					Computed:    true,
					Description: "Unique ID for each target generated by the server.",
				},
				"target_name": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Name of the target.",
				},
				"target_color": {
					Type:        schema.TypeString,
					Required:    true,
					Description: "Hex color code for the target (e.g. #33CC00).",
				},
				"target_condition": {
					Type:        schema.TypeInt,
					Required:    true,
					Description: "SLA target condition constant.",
				},
				"target_value": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Target value for this SLA target.",
				},
			},
		},
	},
	"slo_availability": {
		Type:        schema.TypeList,
		Optional:    true,
		MaxItems:    1,
		Description: "SLA target for monitor availability. Optional if the chosen SLA type is composite.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"availability": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Availability target value.",
				},
				"condition": {
					Type:        schema.TypeInt,
					Required:    true,
					Description: "SLA target condition constant.",
				},
				"weightage": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Weightage in percentage.",
				},
			},
		},
	},
	"slo_responsetime": {
		Type:        schema.TypeList,
		Optional:    true,
		MaxItems:    1,
		Description: "SLA target for monitor response time. Optional if the chosen SLA type is composite.",
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"responsetime": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Response time target value.",
				},
				"time_available": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Time available value.",
				},
				"condition": {
					Type:        schema.TypeInt,
					Required:    true,
					Description: "SLA target condition constant.",
				},
				"weightage": {
					Type:        schema.TypeFloat,
					Required:    true,
					Description: "Weightage in percentage.",
				},
			},
		},
	},
	// Computed
	"sla_id": {
		Type:        schema.TypeString,
		Computed:    true,
		Description: "Unique ID generated by the server for the SLA.",
	},
}

func ResourceSite24x7SLASetting() *schema.Resource {
	return &schema.Resource{
		Create: resourceSite24x7SLASettingCreate,
		Read:   resourceSite24x7SLASettingRead,
		Update: resourceSite24x7SLASettingUpdate,
		Delete: resourceSite24x7SLASettingDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},
		Schema: slaSettingSchema,
	}
}

func resourceSite24x7SLASettingCreate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	sla := resourceDataToSLASetting(d)

	created, err := client.SLASetting().Create(sla)
	if err != nil {
		return err
	}

	d.SetId(created.SLAID)
	return resourceSite24x7SLASettingRead(d, meta)
}

func resourceSite24x7SLASettingRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	sla, err := client.SLASetting().Get(d.Id())
	if err != nil {
		return err
	}

	updateSLASettingResourceData(d, sla)
	return nil
}

func resourceSite24x7SLASettingUpdate(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	sla := resourceDataToSLASetting(d)
	sla.SLAID = d.Id()

	updated, err := client.SLASetting().Update(sla)
	if err != nil {
		return err
	}

	d.SetId(updated.SLAID)
	return resourceSite24x7SLASettingRead(d, meta)
}

func resourceSite24x7SLASettingDelete(d *schema.ResourceData, meta interface{}) error {
	client := meta.(site24x7.Client)

	err := client.SLASetting().Delete(d.Id())
	if err != nil {
		return err
	}

	d.SetId("")
	return nil
}

func resourceDataToSLASetting(d *schema.ResourceData) *api.SLASetting {
	sla := &api.SLASetting{
		DisplayName:   d.Get("display_name").(string),
		Type:          d.Get("type").(int),
		SelectionType: d.Get("selection_type").(int),
	}

	if v, ok := d.GetOk("description"); ok {
		sla.Description = v.(string)
	}
	if v, ok := d.GetOk("business_hours_id"); ok {
		sla.BusinessHoursID = v.(string)
	}

	// monitors
	if v, ok := d.GetOk("monitors"); ok {
		monitorsList := v.([]interface{})
		monitors := make([]string, len(monitorsList))
		for i, m := range monitorsList {
			monitors[i] = m.(string)
		}
		sla.Monitors = monitors
	}

	// monitor_groups
	if v, ok := d.GetOk("monitor_groups"); ok {
		groupsList := v.([]interface{})
		groups := make([]string, len(groupsList))
		for i, g := range groupsList {
			groups[i] = g.(string)
		}
		sla.MonitorGroups = groups
	}

	// sla_targets
	slaTargetsList := d.Get("sla_targets").([]interface{})
	slaTargets := make([]api.SLATarget, len(slaTargetsList))
	for i, item := range slaTargetsList {
		t := item.(map[string]interface{})
		slaTargets[i] = api.SLATarget{
			TargetName:      t["target_name"].(string),
			TargetColor:     t["target_color"].(string),
			TargetCondition: t["target_condition"].(int),
			TargetValue:     t["target_value"].(float64),
		}
	}
	sla.SLATargets = slaTargets

	// slo_availability
	if v, ok := d.GetOk("slo_availability"); ok {
		availList := v.([]interface{})
		if len(availList) > 0 {
			a := availList[0].(map[string]interface{})
			sla.SLOAvailability = &api.SLOAvailability{
				Availability: a["availability"].(float64),
				Condition:    a["condition"].(int),
				Weightage:    a["weightage"].(float64),
			}
		}
	}

	// slo_responsetime
	if v, ok := d.GetOk("slo_responsetime"); ok {
		rtList := v.([]interface{})
		if len(rtList) > 0 {
			r := rtList[0].(map[string]interface{})
			sla.SLOResponseTime = &api.SLOResponseTime{
				ResponseTime:  r["responsetime"].(float64),
				TimeAvailable: r["time_available"].(float64),
				Condition:     r["condition"].(int),
				Weightage:     r["weightage"].(float64),
			}
		}
	}

	return sla
}

func updateSLASettingResourceData(d *schema.ResourceData, sla *api.SLASetting) {
	d.Set("sla_id", sla.SLAID)
	d.Set("display_name", sla.DisplayName)
	d.Set("type", sla.Type)
	d.Set("description", sla.Description)
	d.Set("selection_type", sla.SelectionType)
	d.Set("business_hours_id", sla.BusinessHoursID)

	if sla.Monitors != nil {
		d.Set("monitors", sla.Monitors)
	}
	if sla.MonitorGroups != nil {
		d.Set("monitor_groups", sla.MonitorGroups)
	}

	// sla_targets
	if sla.SLATargets != nil {
		targets := make([]map[string]interface{}, len(sla.SLATargets))
		for i, t := range sla.SLATargets {
			targets[i] = map[string]interface{}{
				"target_id":        t.TargetID,
				"target_name":      t.TargetName,
				"target_color":     t.TargetColor,
				"target_condition": t.TargetCondition,
				"target_value":     t.TargetValue,
			}
		}
		d.Set("sla_targets", targets)
	}

	// slo_availability
	if sla.SLOAvailability != nil {
		d.Set("slo_availability", []map[string]interface{}{
			{
				"availability": sla.SLOAvailability.Availability,
				"condition":    sla.SLOAvailability.Condition,
				"weightage":    sla.SLOAvailability.Weightage,
			},
		})
	}

	// slo_responsetime
	if sla.SLOResponseTime != nil {
		d.Set("slo_responsetime", []map[string]interface{}{
			{
				"responsetime":   sla.SLOResponseTime.ResponseTime,
				"time_available": sla.SLOResponseTime.TimeAvailable,
				"condition":      sla.SLOResponseTime.Condition,
				"weightage":      sla.SLOResponseTime.Weightage,
			},
		})
	}
}
